core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += i18n_patterns (
    path('', include(('posts.urls'))),
    path('', include(('profile_user.urls'))),
    prefix_default_language=False
 ) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
# Django
from django.urls import path

# View
from . import views


app_name = 'post'

urlpatterns = [
    path(
        route='',
        view=views.Home.as_view(),
        name='home'
    ),
    path(
        route='about/',
        view=views.About.as_view(),
        name='about'
    ),
    path(
        route='post',
        view=views.ListPosts.as_view(),
        name='index'
    ),
    path(
        route='create/new/post/',
        view=views.CreatePostView.as_view(),
        name='new_post'
    ),
    path(
        route='contact',
        view=views.ContactView.as_view(),
        name='contact'
    ),
    path(
        route='register',
        view=views.RegisterBetaView.as_view(),
        name='register'
    ),
]

posts/urls.py
# Django
from django.urls import path

# View
from . import views


app_name = 'posts'

urlpatterns = [
    path(
        route='',
        view=views.Home.as_view(),
        name='home'
    ),
    path(
        route='about/',
        view=views.About.as_view(),
        name='about'
    ),
    path(
        route='post',
        view=views.ListPosts.as_view(),
        name='home_login_posts'
    ),
    path(
        route='create/new/posts/',
        view=views.CreatePostsView.as_view(),
        name='new_posts'
    ),
    path(
        route='contact',
        view=views.ContactView.as_view(),
        name='contact'
    ),
    path(
        route='register',
        view=views.RegisterBetaView.as_view(),
        name='register'
    ),
]

profile_user/urls.py
# Django
from django.urls import path

# View
from . import views


app_name = 'users'

urlpatterns = [

    path(
        route='login/',
        view=views.LoginView.as_view(),
        name='login'
    ),
    path(
        route='signup/',
        view=views.SignupView.as_view(),
        name='signup'
    ),
    path(
        route='logout/',
        view=views.LogoutView.as_view(),
        name='logout'
    ),
    path(
        route='update/user/',
        view=views.UpdateProfileView.as_view(),
        name='update_user'
    ),
    path(
        route='change_password/user/',
        view=views.UserPasswordChangeView.as_view(),
        name='change_password'
    ),
    path(
        route='dashboard/user/<int:pk>/',
        view=views.ListDashboarUser.as_view(),
        name='dashboard_user'
    ),
]

post/models.py
from django.db import models
from profile_user.models import User, ProfileUser


class Post(models.Model):
    """Post model."""

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    profile = models.ForeignKey(ProfileUser, on_delete=models.CASCADE)

    title = models.CharField(max_length=255)
    photo = models.ImageField(upload_to='posts/photos')
    description = models.TextField(max_length=500, blank=True)

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        """Return title and username."""
        return '{} by @{}'.format(self.title, self.user.username)

post/forms.py
# Django
from django import forms

# model
from .models import Post
from profile_user.models import ModelDataBeta


class PostForm(forms.ModelForm):
    """Post model form."""

    class Meta:
        """Form settings."""

        model = Post
        fields = ('user', 'profile', 'title', 'photo', 'description')
        widgets = {
            
            'title' : forms.TextInput(attrs={'class':'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'}),
            'photo' : forms.FileInput(attrs={'class':'block w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50 dark:text-gray-400 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400'}),
            'description' : forms.Textarea(attrs={'class':'block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500', 'placeholder': 'Write a post description here...'}),
        }


class DataBetaForm(forms.ModelForm):
    """Post model Data Beta."""

    class Meta:
        """Form settings."""

        model = ModelDataBeta
        exclude = ['is_valid']
        widgets = {
            
            'first_name' : forms.TextInput(attrs={'class':'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'}),
            'last_name' : forms.TextInput(attrs={'class':'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'}), 
            'document_type' : forms.Select(attrs={'class':'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'}),
            'document_number' : forms.NumberInput(attrs={'class':'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'}),
            'email' : forms.EmailInput(attrs={'class':'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'}),
            'phone_number' : forms.NumberInput(attrs={'class':'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'}),
            'city' : forms.TextInput(attrs={'class':'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'}),
            'address' : forms.TextInput(attrs={'class':'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'}),
            'neighborhood' : forms.TextInput(attrs={'class':'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'}), 
            'occupation' : forms.Textarea(attrs={'class':'block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500', 'placeholder': 'Comentanos a que te dedicas'}),

        }

posts/forms.py
# Django
from django import forms
# model
from .models import Posts
from profile_user.models import ModelDataBeta


class PostsFormCreate(forms.ModelForm):
    """Post model form."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for form in self.visible_fields():
            form.field.widget.attrs['class'] = 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'
        self.fields['media_file'].widget.attrs['class'] = 'block w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50 dark:text-gray-400 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400'
        self.fields['media_file'].widget.attrs['accept'] = 'image/png, .jpeg, .jpg, image/gif, .f4v, .MOV,.avi, .mp4, .webm, .mkv, .f4v'

    class Meta:
        """Form settings."""       

        model = Posts
        fields = ('user', 'title', 'media_file', 'description')         


class DataBetaForm(forms.ModelForm):
    """Post model Data Beta."""

    def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)

            for form in self.visible_fields():
                form.field.widget.attrs['class'] = 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'
            self.fields['occupation'].widget.attrs['placeholder'] = 'Comentanos a que te dedicas....'

    class Meta:
        """Form settings."""

        model = ModelDataBeta
        exclude = ['is_valid']
        widgets = {
            'first_name' : forms.TextInput(),
            'last_name' : forms.TextInput(), 
            'document_type' : forms.Select(),
            'document_number' : forms.NumberInput(),
            'email' : forms.EmailInput(),
            'phone_number' : forms.NumberInput(),
            'city' : forms.TextInput(),
            'address' : forms.TextInput(),
            'neighborhood' : forms.TextInput(), 
            'occupation' : forms.Textarea(),
        }

post/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, ListView, TemplateView, View, FormView
from django.urls import reverse_lazy
from django.core.mail import EmailMultiAlternatives
from django.shortcuts import render
from django.urls import reverse
from django.conf import settings

# local
from .forms import PostForm, DataBetaForm
from .models import Post


class Home(TemplateView):
    """Return home page"""

    template_name = 'home.html'
    

class About(TemplateView):
    """Return about page"""

    template_name = 'about.html'


class ListPosts(LoginRequiredMixin, ListView):
    """Return all published posts."""

    template_name = 'posts/home_login_post.html'
    model = Post
    ordering = ('-created',)
    context_object_name = 'posts'


class CreatePostView(LoginRequiredMixin, CreateView):
    """Create a new post."""

    template_name = 'posts/create_post.html'
    form_class = PostForm
    success_url = reverse_lazy('post:index')

    def get_context_data(self, **kwargs):
        """Add user and profile to context."""
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        context['profile'] = self.request.user.profileuser
        return context


class ContactView(View):
    """view to send form mail"""
           
    def get(self, request, *args, **kwargs):
        
        return render (request, 'contact.html', context={})

    def post(self, request, *args, **kwargs):

        full_name = self.request.POST['full_name']
        email = self.request.POST['email']
        number = self.request.POST['number']
        subject = self.request.POST['subject']
        content = self.request.POST['content']

        if full_name and email and number and object and content :

            from_email = settings.EMAIL_HOST_USER
            text_content = "This is an important message."
            html_content = "<p>Nombre: {} <br> Asunto: {} <br> Telefono: {} <br>Email:<strong> {} </strong><br> Mensaje:<br> {}.</p>".format(full_name, subject, number, email, content)
            msg = EmailMultiAlternatives('Contac WEb Guiatec {}'.format(full_name), text_content, from_email, [from_email])
            msg.attach_alternative(html_content, "text/html")
            msg.send()

            return render (request, 'contact.html', context={'form_valid':True})
        
        return render (request, 'contact.html', context={})
    

class RegisterBetaView(FormView):
    """User signup view."""

    template_name = 'users/data_beta.html'
    form_class = DataBetaForm

    def form_valid(self, form):
        """Save form data."""
        form.save()
        return super().form_valid(form)   

    def get_success_url(self):
        url = "%s?register=register_valid" % reverse('post:register')
        return url 

posts/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, ListView, TemplateView, View, FormView
from django.urls import reverse_lazy
from django.core.mail import EmailMultiAlternatives
from django.shortcuts import render, redirect
from django.urls import reverse
from django.conf import settings
from django.utils.translation import gettext as _
# local
from .forms import PostsFormCreate, DataBetaForm
from .models import Posts


class Home(TemplateView):
    """Return home page"""

    template_name = 'home.html'

    def dispatch(self, request,*args, **kwargs):
        """ user started, redirect to start """

        if request.user.is_authenticated:
            return redirect('posts:home_login_posts')
            
        return super().dispatch(request, *args, **kwargs)
    

class About(TemplateView):
    """Return about page"""

    template_name = 'about.html'

    def dispatch(self, request,*args, **kwargs):
        """ user started, redirect to start """

        if request.user.is_authenticated:
            return redirect('posts:home_login_posts')
            
        return super().dispatch(request, *args, **kwargs)


class ListPosts(LoginRequiredMixin, ListView):
    """Return all published posts."""

    template_name = 'posts/home_login_posts.html'
    model = Posts
    ordering = ('-created',)
    context_object_name = 'posts'
    

class CreatePostsView(LoginRequiredMixin, CreateView):
    """Create a new post."""

    template_name = 'posts/create_posts.html'
    form_class = PostsFormCreate
    success_url = reverse_lazy('posts:home_login_posts')


class ContactView(View):
    """view to send form mail"""

    def dispatch(self, request,*args, **kwargs):
        """ user started, redirect to start """

        if request.user.is_authenticated:
            return redirect('posts:home_login_posts')
            
        return super().dispatch(request, *args, **kwargs)
           
    def get(self, request, *args, **kwargs):
        
        return render (request, 'contact.html', context={})

    def post(self, request, *args, **kwargs):

        full_name = self.request.POST['full_name']
        email = self.request.POST['email']
        number = self.request.POST['number']
        subject = self.request.POST['subject']
        content = self.request.POST['content']

        if full_name and email and number and object and content :

            from_email = settings.EMAIL_HOST_USER
            text_content = "This is an important message."
            html_content = "<p>Nombre: {} <br> Asunto: {} <br> Telefono: {} <br>Email:<strong> {} </strong><br> Mensaje:<br> {}.</p>".format(full_name, subject, number, email, content)
            msg = EmailMultiAlternatives('Contac WEb Guiatec {}'.format(full_name), text_content, from_email, [from_email])
            msg.attach_alternative(html_content, "text/html")
            msg.send()

            return render (request, 'contact.html', context={'form_valid':True})
        
        return render (request, 'contact.html', context={})
    

class RegisterBetaView(FormView):
    """User signup view."""

    template_name = 'users/data_beta.html'
    form_class = DataBetaForm

    def dispatch(self, request,*args, **kwargs):
        """ user started, redirect to start """

        if request.user.is_authenticated:
            return redirect('posts:home_login_posts')
            
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        """Save form data."""
        form.save()
        return super().form_valid(form)   

    def get_success_url(self):
        url = "%s?register=register_valid" % reverse('posts:register')
        return url 

templates/posts/create_post.html
{% extends "_base.html" %}

{% block content %}

<div class="max-w-2xl px-4 mt-2 py-2 mx-auto lg:py-8 border border-gray-500 border-dashed rounded">
   
    <h2 class="mb-4 text-xl font-bold text-gray-900 dark:text-white text-center">Create Post</h2>

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.errors}}

        <input type="hidden" name="user" value="{{ user.pk}}" />
        <input type="hidden" name="profile" value="{{ profile.pk }}" />

        <div class="grid gap-4 mb-4 sm:grid-cols-2 sm:gap-6 sm:mb-5">
            <div class="sm:col-span-2">
                <label for="name" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">{{form.title.label}}</label>
                {{form.title}}
            </div>
            <div class="sm:col-span-2">
                <label for="name" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">{{form.photo.label}}</label>
                {{form.photo}}
            </div>

        </div>
        <div class="sm:col-span-2 pb-4">
            <label for="description" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white text-center">{{form.description.label}}</label>
            {{form.description}}
        </div>
        
 
        <div class="flex items-center space-x-4 justify-center">
            <button type="submit" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                Create
            </button>
            <a href="{% url 'post:index' %}" class="text-red-600 inline-flex items-center hover:text-red-700 border border-red-700 hover:bg-red-600 focus:ring-4 focus:outline-none focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:border-red-500 dark:text-red-500 dark:hover:text-white dark:hover:bg-red-600 dark:focus:ring-red-900">
                
                Cancel
            <a>
        </div>
    </form>

</div>

{% endblock content %}

templates/posts/home_login_post.html
{% extends "_base.html" %}

{% block content %}
    <div class="mt-4 px-2">

        {% for post in posts %}

            <div class="border-r border-l border-t bg-white border-gray-200 shadow-sm dark:bg-gray-800 dark:border-gray-700 justify-between">
                <div class="justify-items-stretch">
                                    
                    <figcaption class="flex items-center justify-center space-x-4 pt-2">
                        <a href="{% url 'users:dashboard_user' post.user.pk %}">
                            <img class="rounded-full w-9 h-9" src="{{ post.profile.picture.url }}" alt="profile picture">                        
                        </a>
                        <div class="space-y-0.5 font-medium dark:text-white text-left">
                            <div>{{ post.user.get_full_name }}</div>
                            <div class="text-sm text-gray-500 dark:text-gray-400">{{ post.user.email }}</div>
                        </div>
                        {% if request.user.username == post.user.username %}

                        <button id="dropdownMenuIconButton" data-dropdown-toggle="dropdownDots" class="inline-flex items-center p-2 text-sm font-medium text-center text-gray-900 bg-white rounded-lg hover:bg-gray-100 focus:ring-4 focus:outline-none dark:text-white focus:ring-gray-50 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-600" type="button"> 
                            <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M10 6a2 2 0 110-4 2 2 0 010 4zM10 12a2 2 0 110-4 2 2 0 010 4zM10 18a2 2 0 110-4 2 2 0 010 4z"></path></svg>
                        </button>
                        
                        <!-- Dropdown menu -->
                        <div id="dropdownDots" class="z-10 hidden bg-white divide-y divide-gray-100 rounded-lg shadow w-28 dark:bg-gray-700 dark:divide-gray-600">
                            <ul class="py-2 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="dropdownMenuIconButton">
                                <li>
                                <a href="#" class="block px-4 py-1 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Edit</a>
                                </li>
                                <li>
                                <a href="#" class="block px-4 py-1 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Delete</a>
                                </li>
                            </ul>
                        </div>
                        {% endif %}                      
                        
                    </figcaption> 
                        
                    <div class="flex items-center text-center justify-center pb-1">
                        <svg aria-hidden="true" class="w-5 h-5 text-yellow-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>First star</title><path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"></path></svg>
                        <svg aria-hidden="true" class="w-5 h-5 text-yellow-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Second star</title><path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"></path></svg>
                        <svg aria-hidden="true" class="w-5 h-5 text-yellow-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Third star</title><path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"></path></svg>
                        <svg aria-hidden="true" class="w-5 h-5 text-yellow-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Fourth star</title><path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"></path></svg>
                        <svg aria-hidden="true" class="w-5 h-5 text-gray-300 dark:text-gray-500" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Fifth star</title><path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"></path></svg>
                    </div>                
                    
                </div>

            </div>
            <div class="grid mb-4 border-r border-l border-b border-gray-200 shadow-sm dark:border-gray-700 md:mb-8 lg:grid-cols-2">
                        
                <div class="w-full bg-white rounded-l-lg dark:bg-gray-800 dark:border-gray-700 text-center justify-center">

                    <img class="w-full h-auto max-h-screen" src="{{ post.photo.url }}" alt="image description">
                    
                </div>

                <figure class="flex flex-col items-center justify-center bg-white dark:bg-gray-800 dark:border-gray-700 p-2">

                    <blockquote class="max-w-2xl text-gray-500 dark:text-gray-400">
                        <h3 class="text-lg font-semibold text-gray-900 dark:text-white">{{ post.title }}</h3>
                        <p class="text-xs mb-2 text-gray-500 dark:text-gray-400">{{post.created}}</p>
                        <p class="text-justify text-sm">{{ post.description }}</p>
                    </blockquote>
                    
                </figure>

            </div>
            
        {% endfor %}
    </div>

{% endblock content %}