core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += i18n_patterns (
    path('', include(('posts.urls'))),
    path('', include(('profile_user.urls'))),
    prefix_default_language=False
 ) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
# Django
from django.urls import path

# View
from . import views


app_name = 'posts'

urlpatterns = [
    path(
        route='',
        view=views.Home.as_view(),
        name='home'
    ),
    path(
        route='about/',
        view=views.About.as_view(),
        name='about'
    ),
    path(
        route='post',
        view=views.ListPosts.as_view(),
        name='home_login_posts'
    ),
    path(
        route='create/new/posts/',
        view=views.CreatePostsView.as_view(),
        name='new_posts'
    ),
    path(
        route='contact',
        view=views.ContactView.as_view(),
        name='contact'
    ),
    path(
        route='register',
        view=views.RegisterBetaView.as_view(),
        name='register'
    ),
]

profile_user/urls.py
# Django
from django.urls import path

# View
from . import views


app_name = 'users'

urlpatterns = [

    path(
        route='login/',
        view=views.LoginView.as_view(),
        name='login'
    ),
    path(
        route='signup/',
        view=views.SignupView.as_view(),
        name='signup'
    ),
    path(
        route='logout/',
        view=views.LogoutView.as_view(),
        name='logout'
    ),
    path(
        route='update/user/',
        view=views.UpdateProfileView.as_view(),
        name='update_user'
    ),
    path(
        route='change_password/user/',
        view=views.UserPasswordChangeView.as_view(),
        name='change_password'
    ),
    path(
        route='dashboard/user/<int:pk>/',
        view=views.ListDashboarUser.as_view(),
        name='dashboard_user'
    ),
]

templates/_base.html
{% load compress %}
{% load static %}
{% load i18n %}


<!DOCTYPE html>
<html lang="en">

    <head>

        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <title>
            {% block content_title %}
			{% endblock content_title %}
        </title>

        {% compress css %}
            <link rel="stylesheet" href="{% static 'src/output.css' %}">
        {% endcompress %}

        <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/flowbite.min.css"  rel="stylesheet" />

        <script>
            // On page load or when changing themes, best to add inline in `head` to avoid FOUC
            if (localStorage.getItem('color-theme') === 'dark' || (!('color-theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
                document.documentElement.classList.add('dark');
            } else {
                document.documentElement.classList.remove('dark')
            }
        </script>
    </head>
    
    <body class="bg-gray-10 dark:bg-gray-700">

        {% if request.user.is_anonymous %}
            {% include "nav_home.html" %}
        {% else %}    
            {% include "nav_login.html" %}
        {% endif %}    
        
        <main class="{% if request.user.is_anonymous %}p-2{% else %}pt-8 mt-8 sm:ml-64{% endif %}">
            
            <div class="{% if request.user.is_anonymous %}py-2{% else %}pt-4 mt-4{% endif %}border-gray-200 dark:border-gray-700">                
                {% block content %}
                {% endblock content %}
            </div>
            
        </main>       

        {% if request.user.is_anonymous %}
            {% include "footer_home.html" %}
        {% endif %}    

        <script>
            var themeToggleDarkIcon = document.getElementById('theme-toggle-dark-icon');
            var themeToggleLightIcon = document.getElementById('theme-toggle-light-icon');
    
            // Change the icons inside the button based on previous settings
            if (localStorage.getItem('color-theme') === 'dark' || (!('color-theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
                themeToggleLightIcon.classList.remove('hidden');
            } else {
                themeToggleDarkIcon.classList.remove('hidden');
            }
    
            var themeToggleBtn = document.getElementById('theme-toggle');
    
            themeToggleBtn.addEventListener('click', function() {
    
                // toggle icons inside button
                themeToggleDarkIcon.classList.toggle('hidden');
                themeToggleLightIcon.classList.toggle('hidden');
    
                // if set via local storage previously
                if (localStorage.getItem('color-theme')) {
                    if (localStorage.getItem('color-theme') === 'light') {
                        document.documentElement.classList.add('dark');
                        localStorage.setItem('color-theme', 'dark');
                    } else {
                        document.documentElement.classList.remove('dark');
                        localStorage.setItem('color-theme', 'light');
                    }
    
                // if NOT set via local storage previously
                } else {
                    if (document.documentElement.classList.contains('dark')) {
                        document.documentElement.classList.remove('dark');
                        localStorage.setItem('color-theme', 'light');
                    } else {
                        document.documentElement.classList.add('dark');
                        localStorage.setItem('color-theme', 'dark');
                    }
                }
                
            });
        </script>
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/flowbite.min.js"></script>
        <script src="https://code.jquery.com/jquery-3.7.0.js" integrity="sha256-JlqSTELeR4TLqP0OG9dxM7yDPqX1ox/HfgiSLBj8+kM=" crossorigin="anonymous"></script>
        {% block javascript %}
        {% endblock javascript %}
    </body>

</html>

templates/_base_home.html
<!-- templates/_base.html -->
{% load compress %}
{% load static %}

<!DOCTYPE html>
<html lang="en">

    <head>

        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <title>
            {% block content_title %}
			{% endblock content_title %}
        </title>

        {% compress css %}
            <link rel="stylesheet" href="{% static 'src/output.css' %}">
        {% endcompress %}

        <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.4/flowbite.min.css"  rel="stylesheet" />

        <script>
            // On page load or when changing themes, best to add inline in `head` to avoid FOUC
            if (localStorage.getItem('color-theme') === 'dark' || (!('color-theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
                document.documentElement.classList.add('dark');
            } else {
                document.documentElement.classList.remove('dark')
            }
        </script>
        
    </head>
    
    <body class="bg-gray-50 dark:bg-gray-900">

        {% include "nav_home.html" %}

        <main class="bg-gray-50 dark:bg-gray-700 px-2 pt-8">
            
            {% block content %}
            {% endblock content %}
            
		</main>
           
        {% include "footer_home.html" %}

        <script>
            var themeToggleDarkIcon = document.getElementById('theme-toggle-dark-icon');
            var themeToggleLightIcon = document.getElementById('theme-toggle-light-icon');
    
            // Change the icons inside the button based on previous settings
            if (localStorage.getItem('color-theme') === 'dark' || (!('color-theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
                themeToggleLightIcon.classList.remove('hidden');
            } else {
                themeToggleDarkIcon.classList.remove('hidden');
            }
    
            var themeToggleBtn = document.getElementById('theme-toggle');
    
            themeToggleBtn.addEventListener('click', function() {
    
                // toggle icons inside button
                themeToggleDarkIcon.classList.toggle('hidden');
                themeToggleLightIcon.classList.toggle('hidden');
    
                // if set via local storage previously
                if (localStorage.getItem('color-theme')) {
                    if (localStorage.getItem('color-theme') === 'light') {
                        document.documentElement.classList.add('dark');
                        localStorage.setItem('color-theme', 'dark');
                    } else {
                        document.documentElement.classList.remove('dark');
                        localStorage.setItem('color-theme', 'light');
                    }
    
                // if NOT set via local storage previously
                } else {
                    if (document.documentElement.classList.contains('dark')) {
                        document.documentElement.classList.remove('dark');
                        localStorage.setItem('color-theme', 'light');
                    } else {
                        document.documentElement.classList.add('dark');
                        localStorage.setItem('color-theme', 'dark');
                    }
                }
                
            });
        </script>
        
        <script 
            src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.4/flowbite.min.js">
        </script>

    </body>

</html>

templates/footer_home.html
{% load static %}
<footer class="bg-white border-t border-yellow-300 dark:bg-gray-900">
    <div class="text-center mt-4 mb-2">
        <h2 class="mb-4 text-4xl font-extrabold text-gray-900 dark:text-white md:text-5xl lg:text-6xl"><span class="text-transparent bg-clip-text bg-gradient-to-r to-emerald-600 from-sky-400">Puente Laboral</span></h2>
        <h3 class="text-gray-900 dark:text-white text-xl md:text-3xl font-bold">Conectando talentos, creando oportunidades.</h3>
    </div>

    <div id="gallery" class="relative w-full mb-4" data-carousel="slide">
        <!-- Carousel wrapper -->
        <div class="relative h-56 overflow-hidden rounded-md md:h-96">
            <!-- Item 0 -->
            <div class="hidden duration-700 ease-in-out" data-carousel-item="active">
                <a href="{% static 'logo/logo_c_800.png' %}">
                    <img class="w-full p-8 max-w-md dark:hidden mx-auto absolute block h-auto -translate-x-1/2 -translate-y-1/2 top-1/2 left-1/2" src="https://guiatec.cloud/wp-content/uploads/2023/05/logo_c.webp" alt="dashboard image">
                    <img class="w-full p-8  max-w-md hidden dark:block absolute h-auto -translate-x-1/2 -translate-y-1/2 top-1/2 left-1/2" src="https://guiatec.cloud/wp-content/uploads/2023/05/logo_b.webp" alt="dashboard image"> 
                </a>
            </div>
            <!-- Item 1 -->
            <div class="hidden duration-700 ease-in-out" data-carousel-item>
                <img src="https://guiatec.cloud/wp-content/uploads/2023/05/tb1.webp" class="absolute block max-w-full h-auto -translate-x-1/2 -translate-y-1/2 top-1/2 left-1/2" alt="">
            </div>
            <!-- Item 2 -->
            <div class="hidden duration-700 ease-in-out" data-carousel-item>
                <img src="https://guiatec.cloud/wp-content/uploads/2023/05/electrician-repair-electricity-1080554-1024x682.jpg" class="absolute block max-w-full h-auto -translate-x-1/2 -translate-y-1/2 top-1/2 left-1/2" alt="">
            </div>
            <!-- Item 3 -->
            <div class="hidden duration-700 ease-in-out" data-carousel-item>
                <img src="https://guiatec.cloud/wp-content/uploads/2023/05/img1-1024x683.webp" class="absolute block max-w-full h-auto -translate-x-1/2 -translate-y-1/2 top-1/2 left-1/2" alt="">
            </div>
            <!-- Item 4 -->
            <div class="hidden duration-700 ease-in-out" data-carousel-item>
                <img src="https://guiatec.cloud/wp-content/uploads/2023/05/img2-1.webp" class="absolute block max-w-full h-auto -translate-x-1/2 -translate-y-1/2 top-1/2 left-1/2" alt="">
            </div>
            <!-- Item 5 -->
            <div class="hidden duration-700 ease-in-out" data-carousel-item>
                <img src="https://guiatec.cloud/wp-content/uploads/2023/05/img3.webp" class="absolute block max-w-full h-auto -translate-x-1/2 -translate-y-1/2 top-1/2 left-1/2" alt="">
            </div>
            <!-- Item 6 -->
            <div class="hidden duration-700 ease-in-out" data-carousel-item>
                <img src="https://guiatec.cloud/wp-content/uploads/2023/05/img4.webp" class="absolute block max-w-full h-auto -translate-x-1/2 -translate-y-1/2 top-1/2 left-1/2" alt="">
            </div>
            <!-- Item 6 -->
            <div class="hidden duration-700 ease-in-out" data-carousel-item>
                <img src="https://guiatec.cloud/wp-content/uploads/2023/05/img5.webp" class="absolute block max-w-full h-auto -translate-x-1/2 -translate-y-1/2 top-1/2 left-1/2" alt="">
            </div>
        </div>
        <!-- Slider controls -->
        <button type="button" class="absolute top-0 left-0 z-30 flex items-center justify-center h-full px-4 cursor-pointer group focus:outline-none" data-carousel-prev>
            <span class="inline-flex items-center justify-center w-10 h-10 rounded-full bg-white/30 dark:bg-gray-800/30 group-hover:bg-white/50 dark:group-hover:bg-gray-800/60 group-focus:ring-4 group-focus:ring-white dark:group-focus:ring-gray-800/70 group-focus:outline-none">
                <svg aria-hidden="true" class="w-6 h-6 text-blue-600 dark:text-gray-200" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"></path></svg>
                <span class="sr-only">Anterior</span>
            </span>
        </button>
        <button type="button" class="absolute top-0 right-0 z-30 flex items-center justify-center h-full px-4 cursor-pointer group focus:outline-none" data-carousel-next>
            <span class="inline-flex items-center justify-center w-10 h-10 rounded-full bg-white/30 dark:bg-gray-800/30 group-hover:bg-white/50 dark:group-hover:bg-gray-800/60 group-focus:ring-4 group-focus:ring-white dark:group-focus:ring-gray-800/70 group-focus:outline-none">
                <svg aria-hidden="true" class="w-6 h-6 text-blue-600 dark:text-gray-200" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"></path></svg>
                <span class="sr-only">Sigueinte</span>
            </span>
        </button>
    </div>

    <div class="w-full max-w-screen-xl mx-auto p-4">
        <div class="sm:flex sm:items-center sm:justify-between">
            <a href="{% url 'posts:home' %}" class="flex items-center mb-4 ml-0 sm:ml-4 sm:mb-0">
                
                <img  class="h-10 mr-3 hidden dark:block" src="https://guiatec.cloud/wp-content/uploads/2023/05/logo_p_b.webp" alt="FlowBite Logo" />                    
                <img class="mr-3 btn-toggle h-10 dark:hidden" src="https://guiatec.cloud/wp-content/uploads/2023/05/logo_p_c.webp" alt="logo">
                <span class="self-center text-xl font-semibold whitespace-nowrap dark:text-white">Puente Laboral</span>
            </a>
            <ul class="flex flex-wrap items-center mb-6 mr-4 text-sm font-medium text-gray-500 sm:mb-0 dark:text-gray-400">
                <li>
                    <a href="{% url 'posts:home' %}" class="mr-4 hover:underline md:mr-6 ">Inicio</a>
                </li>
                <li>
                    <a href="{% url 'posts:about' %}" class="mr-4 hover:underline md:mr-6">Acerca de</a>
                </li>
                <li>
                    <a href="{% url 'posts:register' %}" class="mr-4 hover:underline md:mr-6 ">Regístrate</a>
                </li>
                <li>
                    <a href="{% url 'posts:contact' %}" class="hover:underline">Contáctanos</a>
                </li>
            </ul>
        </div>
        <hr class="my-2 border-blue-600 sm:mx-auto" />
        <span class="block text-sm text-gray-500 sm:text-center dark:text-gray-400">© 2023 <a href="https://flowbite.com/" class="hover:underline">Puente Laboral™</a>. Reservados todos los derechos.</span>
    </div>

</footer>

templates/nav_home.html
{% load static %}

<nav class="bg-white dark:bg-gray-900 w-full z-20 top-0 left-0 border-b border-yellow-400 dark:border-yellow-300">

    <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-2">

        <a href="{% url 'posts:home' %}" class="flex items-center pb-2">
            <img class="btn-toggle h-14 hidden dark:block" 
                src="https://guiatec.cloud/wp-content/uploads/2023/05/logo_p_b.webp"
                alt="logo">
            <img class="btn-toggle h-14 dark:hidden" 
            src="https://guiatec.cloud/wp-content/uploads/2023/05/logo_p_c.webp"
            alt="logo">
            <span class="self-center text-sm whitespace-nowrap dark:text-blue-500 ml-1">Puente Laboral</span>
        </a>
                
        <div class="flex md:order-2 ">

            <button id="theme-toggle" type="button" class="mr-4 text-gray-500 dark:text-gray-200 hover:bg-gray-100 dark:hover:bg-gray-700 focus:outline-none focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-700 rounded-lg text-sm p-2.5">
                <svg id="theme-toggle-dark-icon" class="hidden w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M17.293 13.293A8 8 0 016.707 2.707a8.001 8.001 0 1010.586 10.586z"></path></svg>
                <svg id="theme-toggle-light-icon" class="hidden w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M10 2a1 1 0 011 1v1a1 1 0 11-2 0V3a1 1 0 011-1zm4 8a4 4 0 11-8 0 4 4 0 018 0zm-.464 4.95l.707.707a1 1 0 001.414-1.414l-.707-.707a1 1 0 00-1.414 1.414zm2.12-10.607a1 1 0 010 1.414l-.706.707a1 1 0 11-1.414-1.414l.707-.707a1 1 0 011.414 0zM17 11a1 1 0 100-2h-1a1 1 0 100 2h1zm-7 4a1 1 0 011 1v1a1 1 0 11-2 0v-1a1 1 0 011-1zM5.05 6.464A1 1 0 106.465 5.05l-.708-.707a1 1 0 00-1.414 1.414l.707.707zm1.414 8.486l-.707.707a1 1 0 01-1.414-1.414l.707-.707a1 1 0 011.414 1.414zM4 11a1 1 0 100-2H3a1 1 0 000 2h1z" fill-rule="evenodd" clip-rule="evenodd"></path></svg>
            </button>

            <button data-collapse-toggle="navbar-sticky" type="button" class="inline-flex items-center p-2 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-200 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-sticky" aria-expanded="false">
            <span class="sr-only">Open main menu</span>
            <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path></svg>
            </button>
            
        </div>       
        
        <div class="items-center justify-between hidden w-full md:flex md:w-auto md:order-1" id="navbar-sticky">
            

            <ul class="flex flex-col p-2 md:p-0 mt-2 font-medium border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
                
                <li>
                <a href="{% url 'posts:home' %}" class="block pl-3 pr-4 my-2 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-blue-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Inicio</a>
                </li>
                <li>
                <a href="{% url 'posts:about' %}" class="block pl-3 pr-4 my-2 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-blue-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Acerca de</a>
                </li>
                <li>
                <a href="{% url 'posts:register' %}" class="block pl-3 pr-4 my-2 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-blue-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Regístrate</a>
                </li>
                <li>
                <a href="{% url 'posts:contact' %}" class="block pl-3 pr-4 my-2 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-blue-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Contáctanos</a>
                </li>
                <li>
                <a href="{% url 'users:login' %}" class="block text-white bg-blue-600 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-md text-sm py-1 px-2 my-2 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Ingresar</a>
                </li>
                <li>
                <a href="{% url 'users:signup' %}" class="block text-white bg-green-600 hover:bg-green-800 focus:ring-4 focus:outline-none focus:ring-green-300 font-medium rounded-md text-sm py-1 px-2 my-2 text-center dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800">Unirme</a>
                </li>

            </ul>
        </div>
        
    </div>
</nav>
  