core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += i18n_patterns (
    path('', include(('posts.urls'))),
    path('', include(('profile_user.urls'))),
    prefix_default_language=False
 ) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
# Django
from django.urls import path

# View
from . import views


app_name = 'posts'

urlpatterns = [
    path(
        route='',
        view=views.Home.as_view(),
        name='home'
    ),
    path(
        route='about/',
        view=views.About.as_view(),
        name='about'
    ),
    path(
        route='post',
        view=views.ListPosts.as_view(),
        name='home_login_posts'
    ),
    path(
        route='create/new/posts/',
        view=views.CreatePostsView.as_view(),
        name='new_posts'
    ),
    path(
        route='contact',
        view=views.ContactView.as_view(),
        name='contact'
    ),
    path(
        route='register',
        view=views.RegisterBetaView.as_view(),
        name='register'
    ),
]

profile_user/urls.py
# Django
from django.urls import path

# View
from . import views


app_name = 'users'

urlpatterns = [

    path(
        route='login/',
        view=views.LoginView.as_view(),
        name='login'
    ),
    path(
        route='signup/',
        view=views.SignupView.as_view(),
        name='signup'
    ),
    path(
        route='logout/',
        view=views.LogoutView.as_view(),
        name='logout'
    ),
    path(
        route='update/user/',
        view=views.UpdateProfileView.as_view(),
        name='update_user'
    ),
    path(
        route='change_password/user/',
        view=views.UserPasswordChangeView.as_view(),
        name='change_password'
    ),
    path(
        route='dashboard/user/<int:pk>/',
        view=views.ListDashboarUser.as_view(),
        name='dashboard_user'
    ),
]

templates/users/data_beta.html
{% extends "_base.html" %}
{% load static %}

{% block content_title %}
Regístrate
{% endblock content_title %}

{% block content %}
            
    <div class="w-full mx-auto bg-gray-100 rounded-lg shadow-lg shadow-green-500/50 dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700">

        <div class="p-2 space-y-4 md:space-y-6 sm:p-6">
            {% if request.GET.register == 'register_valid' %}

            <div id="toast-success" class="flex items-center mx-auto w-full max-w-xs p-4 mb-4 text-white bg-blue-600 rounded-lg shadow dark:text-white dark:bg-blue-800" role="alert">
                <div class="inline-flex items-center justify-center flex-shrink-0 w-8 h-8 text-green-500 bg-green-100 rounded-lg dark:bg-green-800 dark:text-green-200">
                    <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path></svg>
                    <span class="sr-only">Check icon</span>
                </div>
                <div class="ml-3 text-sm font-normal">Estarás al tanto de nuestras novedades y te informaremos cuando la aplicación esté disponible.</div>
                <button type="button" class="ml-auto -mx-1.5 -my-1.5 bg-white text-gray-400 hover:text-gray-900 rounded-lg focus:ring-2 focus:ring-gray-300 p-1.5 hover:bg-gray-100 inline-flex h-8 w-8 dark:text-gray-500 dark:hover:text-white dark:bg-gray-800 dark:hover:bg-gray-700" data-dismiss-target="#toast-success" aria-label="Close">
                    <span class="sr-only">Close</span>
                    <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
                </button>
            </div>
            {% endif %}
            
            <h1 class="text-xl text-center font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white">                                                
                ¡Únete a la comunidad de Puente Laboral!  
                Regístrate y mantente informado                      
            </h1>
            
            <form class="space-y-4 md:space-y-6" method="POST" >
                {% csrf_token %}                        
        
                <div>
                    <label 
                        for="first_name" 
                        class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">
                        
                        Nombres*
                        {% if form.first_name.errors %}                                    
                            <span class='text-red-600 text-xs'>{{form.first_name.errors}}</span>
                        {%endif%}
                    </label>
                    {{form.first_name}}
                </div>
                <div>
                    <label 
                        for="last_name" 
                        class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">
        
                        Apellidos*
                        {% if form.last_name.errors %}                                    
                            <span class='text-red-600 text-xs'>{{form.last_name.errors}}</span>
                        {%endif%}
                    </label>
                    {{form.last_name}}
                </div>
                <div class="grid md:grid-cols-2 md:gap-6">
                    <div class="relative z-0 w-full mb-2 group">
                        <label 
                            for="document_type" 
                            class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">
            
                            Tipo de Docuemnto*
                            {% if form.document_type.errors %}                                    
                                <span class='text-red-600 text-xs'>{{form.document_type.errors}}</span>
                            {%endif%}
                        </label>
                        {{form.document_type}}
                    </div>
                    <div class="relative z-0 w-full group">
                        <label 
                            for="document_number" 
                            class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">
            
                            Numero de Docuemnto*
                            {% if form.document_number.errors %}                                    
                                <span class='text-red-600 text-xs'>{{form.document_number.errors}}</span>
                            {%endif%}
                        </label>
                        {{form.document_number}}
                    </div>
                </div>
                <div>
                    <label 
                        for="email" 
                        class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">
        
                        Correo*
                        {% if form.email.errors %}                                    
                            <span class='text-red-600 text-xs'>{{form.email.errors}}</span>
                        {%endif%}
                    </label>
                    {{form.email}}
                </div>
                <div>
                    <label 
                        for="phone_number" 
                        class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">
        
                        Numero de telefono*
                        {% if form.phone_number.errors %}                                    
                            <span class='text-red-600 text-xs'>{{form.phone_number.errors}}</span>
                        {%endif%}
                    </label>
                    {{form.phone_number}}
                </div>
                
                <div class="grid md:grid-cols-2 md:gap-6">
                    <div class="relative z-0 w-full mb-2 group">
                        <label 
                            for="city" 
                            class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">
            
                            Ciudad*
                            {% if form.city.errors %}                                    
                                <span class='text-red-600 text-xs'>{{form.city.errors}}</span>
                            {%endif%}
                        </label>
                        {{form.city}}
                    </div>
                    
                    <div class="relative z-0 w-full group">
                        <label 
                            for="neighborhood" 
                            class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">
            
                            Barrio*
                            {% if form.first_name.errors %}                                    
                                <span class='text-red-600 text-xs'>{{form.neighborhood.errors}}</span>
                            {%endif%}

                        </label>
                        {{form.neighborhood}}
                    </div>
                </div>
                <div>
                    <label 
                        for="address" 
                        class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">
        
                        Dirección*
                        {% if form.address.errors %}                                    
                            <span class='text-red-600 text-xs'>{{form.address.errors}}</span>
                        {%endif%}
                    </label>
                    {{form.address}}
                </div>
                <div>
                    <label 
                        for="occupation" 
                        class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">
        
                        Que Ofreces*
                        {% if form.first_name.errors %}                                    
                            <span class='text-red-600 text-xs'>{{form.occupation.errors}}</span>
                        {%endif%}

                    </label>
                    {{form.occupation}}
                </div>
                <div class="flex items-start mb-2">
                    <div class="flex items-center h-5">
                    <input name="is_valid" id="terms" type="checkbox" class="w-4 h-4 border border-gray-600 rounded bg-gray-50 focus:ring-3 focus:ring-green-400 " required>
                    </div>
                    <label for="terms" class="ml-2 text-xs font-medium text-gray-900 dark:text-white">
                        *Al registrarte, aceptas que tus datos sean tratados según la <a href="https://www.funcionpublica.gov.co/eva/gestornormativo/norma.php?i=49981" target="_bank" class="text-blue-600 hover:underline"> ley 1581 de 2012</a></label>
                </div>

                <div class="grid grid-cols-2 gap-6">
                    <button 
                        type="submit" 
                        class="w-full text-white bg-blue-600 hover:bg-blue-700 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-ring-blue-300 mb-2">
                        Registrar
                    </button>
                    <a 
                        href="{% url 'posts:home' %}" 
                        class="w-full text-white bg-red-600 hover:bg-red-700 focus:ring-4 focus:outline-none focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-ring-red-300 mb-2">
                        Cancelar
                    </a>
                </div>
                
            </form>
            
        </div>                
    </div>

{% endblock content %}

templates/users/login.html
{% extends "_base.html" %}
{% load static %}

{% block content_title %}
Login
{% endblock content_title %}

{% block content%}
    
    <section class="w-full max-w-lg mx-auto py-4">
            
        <!-- 
        <div class="flex items-center my-4 text-2xl font-semibold text-gray-900 dark:text-white">
            <img class="btn-toggle w-24 hidden dark:block" 
            src="{% static 'logo/logo_b.png' %}"
            alt="logo">
            <img class="btn-toggle w-24 dark:hidden" 
            src="{% static 'logo/logo_c.png' %}"
            alt="logo">
        </div> 
        --> 

        <div class="w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700">
            <div class="p-4 space-y-4 md:space-y-6 sm:p-6">
                <h1 class="text-xl text-center font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white">
                                            
                    Ingresar
                    
                </h1>
                
                {% block content_form %}
                <form class="space-y-4 md:space-y-6" method="POST" action="{% url "users:login" %}">
                    {% csrf_token %}
                    {% if form.non_field_errors %}
                        <ul class="text-red-600 text-xs">
                            {% for error in form.non_field_errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
            
                    <div>
                        <label for="username" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Username</label>
                        <input type="text" name="username" id="username" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Username" required="">
                    </div>
                    <div>
                        <label for="password" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Password</label>
                        <input type="password" name="password" id="password" placeholder="••••••••" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" required="">
                    </div>
                    <div class="flex items-center justify-between">
                        
                        <a href="#" class="text-sm font-medium text-blue-600 hover:underline dark:text-blue-500">Forgot password?</a>
                    </div>
                    <button 
                        type="submit" 
                        class="w-full text-white bg-blue-600 hover:bg-blue-700 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-ring-blue-300">
                        Sign in
                    </button>
                    <p class="text-sm font-light text-gray-500 dark:text-gray-400">
                        Don’t have an account yet? <a href="{% url 'users:signup' %}" class="font-medium text-blue-600 hover:underline dark:text-blue-500">Sign up</a>
                    </p>
                </form>
                {% endblock content_form %}
                
            </div>
        </div>

    </section>

{% endblock content %}

templates/users/password_change.html
{% extends "_base.html" %}

{% block content %}
    
    <div class="flex flex-col max-w-lg items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">
        
        <div class="w-full p-6 bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md dark:bg-gray-800 dark:border-gray-700 sm:p-8">
            <h2 class="mb-1 text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white text-center">
                Change Password
            </h2>
            <form class="mt-4 space-y-4 lg:mt-5 md:space-y-5" action="#" method="POST">
                {% csrf_token %}

                <div>
                    <label for="old_password" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">{{form.old_password.label}}</label>
                    {% if form.old_password.errors %}                                    
                        <span class='text-red-600 text-xs'>{{form.old_password.errors}}</span>
                    {%endif%}
                    <input type="password" name="old_password" id="old_password" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="••••••••" required="">
                </div>
                <div>
                    <label for="new_password1" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">{{form.new_password1.label}}</label>
                    <input type="password" name="new_password1" id="new_password1" placeholder="••••••••" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" required="">
                </div>

                <div>
                    <label for="new_password2" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">{{form.new_password2.label}}</label>
                    {% if form.new_password2.errors %}                                    
                        <span class='text-red-600 text-xs'>{{form.new_password2.errors}}</span>
                    {%endif%}
                    <input type="password" name="new_password2" id="new_password2" placeholder="••••••••" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" required="">
                </div>
                <div class="flex items-center space-x-4 justify-center">

                    <button type="submit" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                        Update
                    </button>

                    <a href="{% url 'posts:home_login_posts' %}" class="text-red-600 inline-flex items-center hover:text-red-700 border border-red-700 hover:bg-red-600 focus:ring-4 focus:outline-none focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:border-red-500 dark:text-red-500 dark:hover:text-white dark:hover:bg-red-600 dark:focus:ring-red-900">
                        Cancel
                    <a>
                </div>
            </form>
        </div>
    </div>

{% endblock content %}

templates/users/signup.html
{% extends "_base.html" %}
{% load static %}

{% block content_title %}
Unirme
{% endblock content_title %}

{% block content %}
    
    <section class="w-full max-w-lg mx-auto pt-2">  
            
        <div class="w-full mx-auto bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700">

            <div class="p-4 space-y-4 md:space-y-6 sm:p-6">
                
                <h1 class="text-xl text-center font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white">                                                
                    Crear Cuenta                        
                </h1>

                <form class="space-y-4 md:space-y-6" method="POST" action="{% url "users:signup" %}">
                    {% csrf_token %}
                    
                    {% for field in form%}
                        <div>
                            <label for="{{field.id}}" 
                                class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">
                                
                                {{field.label}}
                                {% if field.errors %}                                    
                                    <span class='text-red-600 text-xs'>{{field.errors}}</span>
                                {%endif%}
                            </label>
                            {{field}}
                        </div>

                    {% endfor %}

                    <button 
                        type="submit" 
                        class="w-full text-white bg-blue-600 hover:bg-blue-700 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-ring-blue-300">
                        Create an account
                    </button>
                    <p class="text-sm font-light text-gray-500 dark:text-gray-400">
                        ¿Ya tienes una cuenta? <a href="{% url 'users:login' %}" class="font-medium text-blue-600 hover:underline dark:text-blue-500">Entre aquí</a>
                    </p>
                </form>
                
            </div>                
        </div>
    </section>

{% endblock content %}